blank_issues_enabled: false
contact_links:
  - name: Ask a question, discuss
    url: https://github.com/jlesage/docker-nginx-proxy-manager/discussions
    about: Get help using this Docker container.
  - name: Documentation
    url: https://github.com/jlesage/docker-nginx-proxy-manager#readme
    about: Documentation about this Docker container.
